vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
[VA-1322](https://vimean.atlassian.net/browse/VA-1322)
There is a status that was added to the `clip` object back in November which we weren't accounting for called `transcode_starting`. It would have just been treated as `NONE` which was probably getting treated similarly to AVAILABLE (or whatever the implementation was in our `default` case).
[The original API Git issue](https://github.vimeows.com/Vimeo/vimeo/issues/17447)
Instead of added a fall through to all of our switch statements (and various `if` statements), we're just adding in a check in the getter method we were already using.
After speaking with @alfiehanssen it seems to make the most sense to just put it right in the getter since `transcode_starting` will always have the same UI implication as `transcoding` (which is …
=> VA-1322 New Status: transcode_starting

vimeo-networking/src/main/java/com/vimeo/networking/model/Privacy.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
[VA-1309](https://vimean.atlassian.net/browse/VA-1309)
https://vimeo.com/blog/post/share-unlisted-videos-with-private-links Vimeo recently introduced Unlisted privacy for Pro/Plus users. We need to reflect that in the app and this library. 
Added the unlisted privacy option. Also added in the password field for password protected videos.
Set a video to unlisted privacy and verify it we can see that new privacy in the app.
=> VA-1309 - unlisted privacy

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java, vimeo-networking/src/main/java/com/vimeo/networking/logging/LoggingInterceptor.java
[VA-1418](https://vimean.atlassian.net/browse/VA-1418)
POST responses are throwing errors
Retrofit can not handle empty responses without the Void type in the Call. Updated our current empty post method to take parameters to be more widely used. Also beefed up the logging - instead of logging an error when there is no body to parse, just don't even attempt to parse.
Run the app and check the logs.
=> VA-1418 changes for empty post responses

README.md, example/src/main/java/com/vimeo/android/networking/example/TestApp.java, vimeo-networking/src/main/java/com/vimeo/networking/Configuration.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VimeoAccount.java
[VA-1304](https://vimean.atlassian.net/browse/VA-1304)
We wanted a simple way for consumers of the library to provide an auth token (provided from the developer console) which would remove the need to make client credentials requests.
* Added an access token to the configuration builder.
* Moved around account setting so the vimeoAccount on the vimeo client has a tighter coupling to the configurationbuilder.accountStore callbacks.
* Added section to the README
* Test the VimeoApp to ensure nothing broke (log in, log out, change users, get client credentials)
* Use the example app and go through some weird auth flows
=> VA-1304 Access Token Auth

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java
[VA-1453](https://vimean.atlassian.net/browse/VA-1453)
Clicking skip on first welcome screen caused crash
We used to persist to accountstore very selectively. I switched it so everything routes through the method that persists to the account store, but it looks like the one circumstance we don't want to persist is when it's a totally empty Account (happens the first time if there is no access token or on any subsequent logout).
Now we only save if the vimeo account isn't totally empty.
I'll also have to change the SHA on client app
* Test a lot of auth flows - log in, log out, close app, log in, close app, open app, logout.
* Test skipping the welcome screen
* Test logging in on the welcome screen
* Ensure that you can still make requests for explore
* Ensure that the correct account …
=> VA-1453 Skip Welcome Crash

example/src/main/java/com/vimeo/android/networking/example/vimeonetworking/TestAccountStore.java, vimeo-networking/src/main/java/com/vimeo/networking/AccountStore.java, vimeo-networking/src/main/java/com/vimeo/networking/Configuration.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/callbacks/AuthCallback.java
[VA-1059](https://vimean.atlassian.net/browse/VA-1059)
Deprecate saving of the password into the account store
Instead of flat out removal, I created secondary methods without password parameters, and deprecated all methods using the password parameter. 
Test in the app PR
=> VA-1059 deprecate password saving

vimeo-networking/src/main/java/com/vimeo/networking/model/VideosPreference.java
[VA-1372](https://vimean.atlassian.net/browse/VA-1372)
Default password not displaying during upload.
Adding global password to VideosPreference object.
Nothing specific to test with this networking ticket alone. Just make sure that video password privacy still works as it used to.
=> VA-1372: Adding global password to VideosPreference object

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/callbacks/VimeoCallback.java
[VA-1428](https://vimean.atlassian.net/browse/VA-1428)
Our cancellations have issues. We should revisit when upgrading to non-beta retrofit
Fixed the cancel jank
Cancel requests, and verify all requests using ```getRetrofitCallback``` show as canceled
=> VA-1428 Cancel issues

vimeo-networking/src/main/java/com/vimeo/networking/model/VodItem.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VodList.java
[VA-1618](https://vimean.atlassian.net/browse/VA-1618)
Create a mode to support a VOD container object.
Added a VodItem object and a VodList object. Only supporting the fields that we need at the moment to support VOD.
Ensure that the project builds as expected and nothing is broken related to existing networking (regression tests pass).
=> VA-1618 Added VOD container model

gradle.properties, gradle/wrapper/gradle-wrapper.properties, vimeo-networking/src/main/java/com/vimeo/networking/Configuration.java, vimeo-networking/src/main/java/com/vimeo/networking/RetrofitClientBuilder.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java
[VA-1654](https://vimean.atlassian.net/browse/VA-1654)
We want to be able to inspect our network requests with Stetho. This means we have to allow our `OkHttpClient` to have a special `StethoInterceptor` to it. Since we construct the client in the networking library, we need to add a hook to set a custom interceptor.
- Added a hook to add an Interceptor that is used across all `OkHttpClient` instances built by our builder.
- Upgraded gradle dist version, added some flags to speed up builds
- add any interceptors you want to the `Configuration` object when initializing `VimeoClient`.
- example:
```
configBuilder.addNetworkInterceptor(new MyInterceptor());
VimeoClient.initialize(configBuilder.build());
```
=> VA-1654 interceptor support

vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
[VA-1622](https://vimean.atlassian.net/browse/VA-1622)
API is adding release_time to the video object for video returned from series connection endpoints. We need to expose this from the networking model so that series videos can display the expected release date.
Added the releaseTime field to the video object.
Nothing to test here.
=> VA-1622 Adding release_time to video

vimeo-networking/src/main/java/com/vimeo/networking/model/Interaction.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
[VA-1622](https://vimean.atlassian.net/browse/VA-1622)
It is possible for VOD objects to have multiple purchase states set simultaneously. We need to account for this and arbitrate properly. A VOD video's purchase type is chosen based on the following priority:
1) trailer
2) purchased
3) both rental and subscription? choose the later expiration, expirations equal? choose subscription
4) subscription
5) rental
The ticket itself doesn't address this, but it is a bucket that I am attaching remaining VOD work to. 
Modified the video.java model object's convenience methods to arbitrate the purchase type and date according to more complex rules. Also, removed some lint errors.
Nothing to test independently here. The changes will have to be tested in conjunction …
=> Adding more robust logic around purchase expiration

vimeo-networking/src/main/java/com/vimeo/networking/Search.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/FacetOptions.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/FacetOptionsCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/SearchFacet.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/SearchFacetCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/SearchResponse.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/SearchResult.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/SearchType.java
[VA-1777](https://vimean.atlassian.net/browse/VA-1777)
We are introducing a new search endpoint ```/search``` for whitelisted apps. This ticket is about integrating that into the mobile app.
I created new models for the search representations, and placed them in a ```model.search``` package. I then created a new Retrofit service, which is accessed through a package-private VimeoClient ```search``` method. The way to access this is through the ```Search``` class.
In order to search you call upon the static ````Search.search()``` method, passing it certain parameters. Similar to the existing ```SearchRefinementBuilder```, there is a ```QueryParameterProvider``` to set parameters and generate a Map.
I left the existing search functionality in place and am not deprecating anything, since this …
=> VA-1777 new search models, search class

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java, vimeo-networking/src/main/java/com/vimeo/networking/model/ConnectionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
[Va-1827](https://vimean.atlassian.net/browse/Va-1827)
Add the playback connection for DRM failure errors
Add the connection as well as a helper to obtain it. Also added back in two constants I removed for 2.3.2, since 2.3.1 needs them still! I added the Deprecated annotation to them to remind us to remove.
=> Va-1827 add failure playback connection

vimeo-networking/src/main/java/com/vimeo/networking/Search.java, vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java
[VA-1795](https://vimean.atlassian.net/browse/VA-1795)
For search, we need to support a new ```container_fields``` filtering parameter.
I added a new constant for the field, and updates ```Search``` to take a new parameter for the container_fields filtering parameter.
Using the Android app, same PR, test the responses
=> VA-1795 add support for container_fields filtering in search

vimeo-networking/src/main/java/com/vimeo/networking/model/BaseResponseList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/CategoryList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/ChannelList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/CommentList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/FeedList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/UserList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VideoList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VodList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/SearchResponse.java
[VA-1844](https://vimean.atlassian.net/browse/VA-1844)
Base response list did not specify that its model class should return the parameterized type that it was of.
Fixed some of the list classes.
Not applicable.
=> Fixed problems in BaseResponseList

vimeo-networking/src/main/java/com/vimeo/networking/GsonDeserializer.java
[VA-1712](https://vimean.atlassian.net/browse/VA-1712)
Add more robust logic around parsing objects from the API
While stag adds extra parsing protection, we need to catch errors being thrown by Gson still. The networking layer has a logging system that will use a provider logger or system.out; we can use that to log any errors encountered in stag. 
Change an object to an array, or vice versa.
=> VA-1712 robust parsing handling

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java
[VA-1829](https://vimean.atlassian.net/browse/VA-1829)
In the fetchVideoSync method, there was no cache control param, so it is defaults to cache. This is bad, because we cannot truly refresh a video.
I overloaded the fetchVideoSync method, so the existing method pulls from network, and there is another method that will allow users to stipulate the cache control.
Download a video from deeplink. Try it again the next day. The video files should not be expired.
=> VA-1829 update fetch video to not pull from cache

vimeo-networking/src/main/java/com/vimeo/networking/model/error/VimeoError.java
[ANDTV-102](https://vimean.atlassian.net/browse/ANDTV-102)
Player refactor came with some DRM state relaying touch ups
I added this helper method for logging vimeo errors when all we care about is just some information to help us find out where a problem is coming from.
Try to play DRM while logged out and see the error spit out in logcat
Example: "Player Show Retry Error: DRM error: No user credentials were provided"
=> ANDTV-102 Vimeo Error Log

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java
[VA-1881](https://vimean.atlassian.net/browse/VA-1881)
BlinkFeed content never loads
The issue is that when fresh installed and never going into the app, a client credentials token is never issued - thus leaving BlinkFeed to try and make requests using basic auth, which fail.
=> VA-1881 adding sync method for client creds

vimeo-networking/src/main/java/com/vimeo/networking/model/ConnectionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Recommendation.java, vimeo-networking/src/main/java/com/vimeo/networking/model/RecommendationList.java, vimeo-networking/src/test/java/com/vimeo/networking/model/RecommendationTest.java
[VA-1741](https://vimean.atlassian.net/browse/VA-1741)
Add the Recommendation response, as defined [here](https://github.vimeows.com/Vimeo-API/api/issues/127).
Add a categories connection as defined [here](https://github.vimeows.com/Vimeo-API/api/issues/150).
Added the connection, created the model, its response list, and a simple unit test for the ```NotNull``` model method.
Run the unit test.
=> VA-1741 add Recommendation model, add categories connection for User

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java
[DTA-26](https://vimean.atlassian.net/browse/DTA-26)
When introducing multiple apps that may be authenticated, we need a way to exchange tokens from one app for another, so users do not need to enter their credentials again.
The API provides a single-sign-on token exchange endpoint, for use by Vimeo's iOS and Android apps. I added a client and service method to support this.
=> DTA-26 add single sign on token exchange

README.md, build.gradle, vimeo-networking/build.gradle, vimeo-networking/src/main/java/com/vimeo/networking/utils/ISO8601.java
[VA-1891](https://vimean.atlassian.net/browse/VA-1891)
Get v1.1.0 release ready
* Added back in ISO8601, deprecated it, and updated its javadoc - this helps prevent a breaking change.
* Updated the ReadMe to show updated method params.
* Updated the ReadMe with new version
* Bump retrofit version to latest
* Tweak gradle to prevent build fail when uploading to bintray
* Verify cert pinning still works with new retrofit update
=> VA-1891 get v1.1.0 release ready

vimeo-networking/src/main/java/com/vimeo/networking/callbacks/VimeoCallback.java
Sometimes when we get an error back from a response, we have a non null but empty error response body. In this case, we throw an exception (and catch it) as we try to parse the empty error.
I am tired of seeing this exception in my logs, so to fix it, I am checking whether the error response is empty, and not trying to parse it if it is. The reason it is empty is that we try to pull from cache and get an error if it is empty or invalid, and since the cache is not sending any sort of response code, the error response is empty.
From a cold start with cache cleared, start the app. Without this change, two or three exceptions will be logged to `System.out` as the error converter is unable to convert empty errors.
=> Smarter error handling

vimeo-networking/src/main/java/com/vimeo/networking/logging/LoggingInterceptor.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VimeoAccount.java, vimeo-networking/src/main/java/com/vimeo/networking/utils/ISO8601Wrapper.java, vimeo-networking/src/main/java/com/vimeo/networking/utils/VimeoNetworkUtil.java
[VA-1963](https://vimean.atlassian.net/browse/VA-1963)
The date deserialization is crashing sometimes because the API seems to send us bad dates.
Wrap the deserialization in a try catch so we can choose whether or not to crash on the client side.
make sure dates still show up correctly
=> VA-1963 wrapping date deserialization

vimeo-networking/src/main/java/com/vimeo/networking/model/Connection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/ConnectionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VideoBadge.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/SearchResult.java, vimeo-networking/src/main/java/com/vimeo/networking/model/vod/Season.java, vimeo-networking/src/main/java/com/vimeo/networking/model/vod/SeasonList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/vod/VodItem.java, vimeo-networking/src/main/java/com/vimeo/networking/model/vod/VodList.java
[VA-1984](https://vimean.atlassian.net/browse/VA-1984)
For VOD Season support, we need to add some models. Also, as a bonus, add the Video Badge representation.
I created 3 models - a ```Season```, ```SeasonList```, and ```VideoBadge```. Since the main model package is growing and we want to do a bunch of refactoring for 2.0.0, I made a vod package for the season models, and moved ```VodItem``` and ```VodList``` into it.
We aren't using the new models anywhere yet, but verify that the app doesn't crash with the package moves - use the mobile PR for that.
=> VA-1984 add VOD season models, move VOD models, add VideoBadge

example/src/main/java/com/vimeo/android/networking/example/vimeonetworking/TestAccountStore.java, vimeo-networking/src/main/java/com/vimeo/networking/AccountStore.java, vimeo-networking/src/main/java/com/vimeo/networking/Configuration.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VimeoAccount.java
[VA-1728](https://vimean.atlassian.net/browse/VA-1728)
We need to make a few adjustments to the networking code to improve auth within the apps
The main aspect of this ticket was to create a synchronous version of the single sign on method, that can be passed a basic auth string. This is needed since this will be called from a background thread within the Android AccountManager system (getAuthToken), and we need the basic auth header of the requesting app, not the basic auth header of the running app - the running app is always the first installed app with a Vimeo AccountManager (authenticator)
Side effect are cleaning up some of the deprecated methods around the AccountStore, and adding annotation.s
Use the VA-1728 branches in vimeo-kit and VimeoMobile to test
=> VA-1728 Improving account manager code

vimeo-networking/src/main/java/com/vimeo/networking/model/ConnectionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/vod/Season.java, vimeo-networking/src/main/java/com/vimeo/networking/model/vod/VodItem.java
[ANDTV-224](https://vimean.atlassian.net/browse/ANDTV-224)
In order to dynamically add seasons to the rows fragment on tv, we will need to get the seasons uri from the API. Also we should have simple helper accessing methods for this.
I added in the connection and some simple helpers for ```VodItem``` and ```Season```
Nothing to test
=> ANDTV-224 Vod Seasons 

vimeo-networking/build.gradle, vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Document.java
[ANDTV-281](https://vimean.atlassian.net/browse/ANDTV-281)
Add API support for several documents, including Terms of Service, Privacy Policy, and the Payment Addendum.
* Updated stag in order to take advantage of package-private members.
* Added a Document model representing the API responses for these documents
* Added a service method to fetch a Document
* Added several VimeoClient methods to fetch the different documents
TODO:
Use the branches of vimeo-kit and vimeo TV of the same name to verify the documents can be fetched and displayed
=> ANDTV-281 adding support for terms and privacy

vimeo-networking/src/main/java/com/vimeo/networking/model/Category.java
[DTA-39](https://vimean.atlassian.net/browse/DTA-39)
For Day Tripper, we want to show the category icon on the cards. We should do this dynamically, as the API recently provided support for this. This PR is about adding that API support. This is not about updating Category and all of its members and methods, this is just about the additional field.
Added in the additional field for the icon, along with a getter.
=> DTA-39 adding category icon

vimeo-networking/src/main/java/com/vimeo/networking/model/Spatial.java
Adding `equals`, `hashCode`, and `toString` for `Spatial` object
=> Adding equals, hashcode, and toString for spatial object

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Connection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/ConnectionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Credit.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/Notification.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/NotificationConstants.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/NotificationList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/NotificationType.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/SubscriptionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/Subscriptions.java
[VA-1849](https://vimean.atlassian.net/browse/VA-1849)
In order to create the notification screen within the Android app, we need to have the models. 
As the API is going to be using the same keys for all types, I broke the types out into an enum and a constants file. I moved the subscription classes into the notification package since they are related.
I created two API issues
* https://github.vimeows.com/Vimeo-API/api/issues/819 the uri is always null
* https://github.vimeows.com/Vimeo-API/api/issues/820 the response doesn't contain the state (new/seen). I will follow up with another networking PR once that is finalized.
=> VA-1849 notification models

vimeo-networking/src/main/java/com/vimeo/networking/model/Credit.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/Notification.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/NotificationType.java
[VA-1850](https://vimean.atlassian.net/browse/VA-1850)
In order to properly handle object updates, we need to add some setters to Notification and Credit
I added setters for the two models, and I fixed a NotificationType bug that associated Likes to Comments
=> VA-1850 Notification updates

vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/NotificationType.java
[VA-2112](https://vimean.atlassian.net/browse/VA-2112)
Adding a toString method to NotificationType enum for analytics
I created a toString and a static method for getting a string key from an enum value for `NotificationType`. I opted for this approach versus a string constructor for the enum values due to the future expansion of types - I don't want the app to crash if we get additional types, instead, the type will be converted to Unknown using this approach.
=> VA-2112 Add toString for notification analytics

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java
[VA-1890](https://vimean.atlassian.net/browse/VA-1890)
We need to issue patch requests for notifications. One of the bodies contains a map, the other a list. Neither request has a return object.
I created a generic `Void` `Call` for patches. I use an `Object` as the body to let it be decided by the consumer what type to pass. I also added a few parameter constants.
=> VA-1890 Patch requests for notifications

vimeo-networking/src/main/java/com/vimeo/networking/model/Privacy.java, vimeo-networking/src/main/java/com/vimeo/networking/utils/PrivacyDeserializer.java, vimeo-networking/src/main/java/com/vimeo/networking/utils/VimeoNetworkUtil.java
Don’t use Stag for serialization of Privacy object
Due to the `Privacy.add` and `Privacy.download` fields being sent from the server as integers, we need to deserialize these as integers and not as booleans. Gson and Stag don't support integer to boolean conversion, so we need to create a custom adapter that does it for us.
=> Don’t use Stag for serialization of Privacy object

vimeo-networking/src/main/java/com/vimeo/networking/model/VideoFile.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VideoFileDeserializer.java, vimeo-networking/src/main/java/com/vimeo/networking/utils/VimeoNetworkUtil.java
[VA-2204](https://vimean.atlassian.net/browse/VA-2204)
We have a crash in the Android app when trying to parse a non-field-filtered `Video` object. This is because we get the `files` array, which contain `VideoFile` objects. Within the files array, these objects contain a `log` property that is an object. We are looking for `log` to be a String. 
I filed an issue with the [API](https://github.vimeows.com/Vimeo-API/api/issues/935) to use Strings everywhere for the `log` fields.
In the meantime, I created a custom `TypeAdapter` and removed `VideoFile` from general Stag processing (the sub-enums still use Stag).
Run with the Android app:
* In the notifications screen, when credited in a video, the list would not render, now it does
* When editing a video setting (title, description, or …
=> VA-2204 Use custom Type Adapter over Stag for VideoFile log issue

fastlane/Fastfile
External PRs break Travis because env vars aren't available to them.
=> Only run Danger when a Github token exists

vimeo-networking/src/main/java/com/vimeo/networking/model/search/BaseSuggestion.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/OndemandSuggestion.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/SuggestionResponse.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/VideoSuggestion.java
[ADF-3](https://vimean.atlassian.net/browse/ADF-3)
We need to create some models to represent the response from `https://api.vimeo.com/suggest`
I created the necessary models, using a base class to contains the `text` field, since all suggestions will always have this. I also added in `toString`, `equals`, and `hashCode` methods.
Using Postman or another rest client, hit `https://api.vimeo.com/suggest?query=cats&video_count=5&ondemand_title_count=5` and compare the response with the models created.
=> ADF-3 Search suggestion models

vimeo-networking/src/main/java/com/vimeo/networking/Search.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java, vimeo-networking/src/test/java/com/vimeo/networking/SearchTest.java
[ADF-4](https://vimean.atlassian.net/browse/ADF-4)
Before we can integrate autocomplete into the Android app, we need to add the necessary groundwork in the networking layer. This ticket is about creating the API call.
I created a simple retrofit service interface and wired it up to a `Search` method, `suggest`. This method takes a query, counts for the number of results to receive per type, and a callback. 
I also created a simple test to validate that null is returned when the query is empty.
You can run the `SearchTest` if you'd like, but there is nothing to test aside from that, yet.
=> ADF-4 autocomplete methods

vimeo-networking/src/main/java/com/vimeo/networking/model/Connection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/ConnectionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/Notification.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/NotificationConnection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/NotificationConstants.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/NotificationList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/NotificationType.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/SubscriptionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/Subscriptions.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/BaseSuggestion.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/OndemandSuggestion.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/SuggestionResponse.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/VideoSuggestion.java
[VA-2203](https://vimean.atlassian.net/browse/VA-2203)
We need to add a new object onto the notification connection for type counts.
Also, somehow my copyright profile got messed up and wasn't adding copyrights, so I went back and added them to files I recently added.
I decided that since the new fields only applied to the notification `Connection`, that it'd be better to remove the fields from `Connection` and make a specialized `NotificationConnection` object. This has all the great fields of `Connection` with the additional properties sent specific to the `notification` connection.
=> VA-2203 Notification connection for type counts

vimeo-networking/src/main/java/com/vimeo/networking/model/ConnectionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/cinema/ProgramContentItem.java, vimeo-networking/src/main/java/com/vimeo/networking/model/cinema/ProgramContentItemList.java
[ANDTV-571](https://vimean.atlassian.net/browse/ANDTV-571)
Create the model objects to support the entirety of the Cinema endpoint beyond just what is needed for the short term. The endpoint documentation is available here:
https://vimean.atlassian.net/wiki/pages/viewpage.action?pageId=69049946
Added ProgramContentItem and ProgramContentItemList to represent the list of objects returned from the cinema endpoint. Modified the ConnectionCollection object to support a field that is returned by the cinema endpoint.
No tests are possible at this time.
=> Adding Cinema ProgramContentItem Support

vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
[ANDTV-581](https://vimean.atlassian.net/browse/ANDTV-581)
[ANDTV-582](https://vimean.atlassian.net/browse/ANDTV-582)
[ANDTV-583](https://vimean.atlassian.net/browse/ANDTV-583)
[ANDTV-594](https://vimean.atlassian.net/browse/ANDTV-594)
Adding a few modifications to support the SVOD prototype. 
In general, this change involves ironing out a few wrinkles around the fact that SVOD and TVOD now co-exist. There were some methods like isTrailer that needed to take that into account as naming and commenting some methods to distinguish the two types. Renaming the public API was ticketed for a future date as I didn't want to introduce any breaking changes at this point since they are not necessary to get the prototype to work. Here is the future ticket:
https://vimean.atlassian.net/browse/ADF-128 …
=> ANDTV-581 Making a few modifications to support SVOD

README.md
Since our default branch is v2.0.0 and we have so many changes ahead of our latest public release, it would be helpful to be able to see at a glance that the latest version of the library is in fact 1.1.0. We can do this by adding a badge to the readme as I have done here.
=> Showing the latest released version as a badge in the readme

vimeo-networking/src/main/java/com/vimeo/networking/model/PictureCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Preferences.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Spatial.java, vimeo-networking/src/main/java/com/vimeo/networking/model/UserBadge.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VideosPreference.java, vimeo-networking/src/main/java/com/vimeo/networking/model/playback/Drm.java, vimeo-networking/src/main/java/com/vimeo/networking/model/playback/Play.java, vimeo-networking/src/main/java/com/vimeo/networking/model/playback/PlayProgress.java
Due to a problem where we didn't use the stag serializer in some code, the field names were all broken because of the `@GsonAdapterKey` annotation. Since we have now replaced that annotation with the `@SerializedName` annotation which is picked up by gson regardless of whether the stag plugin is used, we need to add backwards compatibility for the broken cached json. The only classes that were affected were those that are referenced by `Video` and `VideoFile`.
By using the alternate name scheme, we can add these optional names as json keys to pick up what was broken. When these classes are serialized again, the `value` is used and the `alternate` values are ignored.
=> Backwards compatibility

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java
[VA-2299](https://vimean.atlassian.net/browse/VA-2299)
Commenting was broken due to a mistakenly renamed constant that was changed during conversion to hungarian notation.
The constant was changed back to its correct name (I also searched high and low for other "mXYZ" named constants and did not find any others).
Try to make a comment post and it should now work as expected.
=> Fixing typo that broke commenting

vimeo-networking/build.gradle, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java
[ADF-154](https://vimean.atlassian.net/browse/ADF-154)
In order to begin publicly supporting beta versions of the networking API, the networking library needs to begin identifying itself as the source of requests using the user agent string.
See https://github.vimeows.com/Vimeo-API/api/issues/1141#issuecomment-143397
The format of the user agent is as follows:
```
[Optional consumer supplied UA] VimeoNetworking/version (Java)
```
The version is retrieved at runtime from a generated `BuildConfig` class.
Make a request with the VimeoClient and ensure that the user agent has at least `VimeoNetworking/1.1.0 (Java)` in it.
=> ADF-154 consistent user agent

vimeo-networking/build.gradle, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/utils/BaseUrlInterceptor.java, vimeo-networking/src/main/java/com/vimeo/networking/utils/Preconditions.java, vimeo-networking/src/test/java/com/vimeo/networking/utils/BaseUrlInterceptorTest.java
[ADF-126](https://vimean.atlassian.net/browse/ADF-126)
We would like to start using Drakov (https://github.com/Aconex/drakov) to support mocking API calls. We would like to support changing the host on a per request basis.
There were a few approaches to implementing this support. 
The first would have been to add a URL parameter to every request method in `VimeoService` and to propagate that change outward. This seemed like an extremely disruptive change to make for something that is not going to be used frequently. Additionally, adding it as a parameter on service calls would affect client code negatively, making it more complicated.
A second would be to recreate the retrofit client whenever we needed to change the base URL. This approach was not friendly for consumers that would be …
=> [FEATURE] ADF-126 Drakov support

.travis.yml, fastlane/Fastfile, fastlane/README.md, gradle.properties, vimeo-networking/build.gradle
[CI-450](https://vimean.atlassian.net/browse/CI-450)
Moved version to build.properties for readability
Changed Travis entrypoint to the `entrypoint` Fastlane lane.
Added `publish_artifacts` lane
=> CI-450: publish to JCenter

vimeo-networking/src/main/java/com/vimeo/networking/Configuration.java, vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java
[ADF-159](https://vimean.atlassian.net/browse/ADF-159)
We should remove the ability to set the API version. Clients will automatically get the hardcoded version.
I added a static field in `Vimeo` to hold the API version, and removed the ability to set it using the configuration builder.
=> ADF-159 hardcode api version

vimeo-networking/build.gradle, vimeo-networking/src/main/java/com/vimeo/networking/Configuration.java, vimeo-networking/src/main/java/com/vimeo/networking/RetrofitSetup.java, vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/interceptors/AcceptHeaderInterceptor.java, vimeo-networking/src/main/java/com/vimeo/networking/interceptors/CacheControlInterceptor.java, vimeo-networking/src/main/java/com/vimeo/networking/interceptors/UserAgentInterceptor.java, vimeo-networking/src/test/java/com/vimeo/networking/RetrofitSetupTest.kt
[ADF-202](https://vimean.atlassian.net/browse/ADF-202)
`VimeoClient` is responsible for too much.  This change moves the setting up of Retrofit to a new `RetrofitSetup` class, and pulls various Interceptors into their own classes in a new `interceptors` package.
- New `RetrofitSetup` class used to configure Retrofit.
- new `interceptors` package holding extracted Interceptors.
Make sure you can login and navigate app.  Use Charles proxy to ensure custom headers are being sent as before.
=> ADF-202 Extract Retrofit setup code to new classes

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java
Added endpoints for authenticating a user using a Google `id_token` auth token.
The new Google auth endpoints match the existing Facebook auth endpoints almost exactly other than passing `id_token` instead of `token` param.
Note: these endpoints will only work with the vimeo app not external users of the API.
Verify that a user can:
- Login with a Google auth token
- Join with a Google auth token
[VA-2451](https://vimean.atlassian.net/browse/VA-2451)
=> Google auth endpoints

build.gradle, example-kotlin-android/build.gradle, vimeo-networking/build.gradle
`vimeo-networking/build.gradle` is not picking up new variable rename.  Var seems to be coming from root (App) module instead.  Renaming the var caused full app to stop compiling.  Reverting back to `kotlin_version`.
=> Rename Kotlin gradle var name

vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
[VA-2580](https://vimean.atlassian.net/browse/VA-2580)
It would be good to have a few helper methods on `Video`, to help with determining if a video is live, and if it is ended or streaming.
I added a few helper methods that can be used. For more complicated circumstances, it would be better to grab the `Live` object and perform your own comparisons.
=> Live video helper methods

vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
[VA-2587](https://vimean.atlassian.net/browse/VA-2587)
It would be beneficial to have another helper method on the video to determine if a video is a live video in the prestream state.
Added an extra helper
=> Add Live Video Pre-Stream Helper

vimeo-networking/src/main/java/com/vimeo/networking/model/InteractionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
There is an interaction on the Video object that provides contextual information about the interaction between a Video and a Channel when a video is embedded in a channel stream. It allows the consumer to delete the video from the channel by using a DELETE on the URI of the interaction.
I added the `channel` interaction and called it the "channel membership" interaction.
No testing necessary.
=> Adding the channel membership interaction

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java
`VimeoClient` in many cases should be injectable into a class so that a mock can be used instead for Unit Testing.  Having to mock networking code is a common case.  This PR makes the `VimeoClient` class non-final so that it can more easily mocked during testing.  
- Mockito does have support for mocking final classes but it's an incubating feature that we're told will change its syntax, so probably best not rely on it.
- PowerMock could also be used, but that is know to be a bit of a code-smell in many cases.  Again, not a good thing to force across a large set of tests.
Ideally `VimeoClient` may even be turned into interface vs a class, but that's a much bigger refactoring.
N/A
=> Make VimeoClient non-final

vimeo-networking/src/main/java/com/vimeo/networking/model/LiveTime.java
Business live users have a monthly maximum (in seconds) that can't fit in an int. The side effect of this problem is that business live users are unable to sign into the app.
=> Hot fixing issue with live time data

vimeo-networking/src/main/java/com/vimeo/networking/model/Interaction.java, vimeo-networking/src/main/java/com/vimeo/networking/model/InteractionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
[VA-2686](https://vimean.atlassian.net/browse/VA-2686)
The API team recently added support for a report interaction in the Video response:
https://github.vimeows.com/Vimeo-API/blueprint/commit/e609bff2b914ce5b9175dce6b416b82ddbacd0aa
This ticket is about adding the necessary items to the models of the networking library.
I added models and helper methods for getting report related interactions data.
Confirm that reporting still works in VA-2686-Interaction-Support app branch and that tests in VideoReportingReasonsPresenterTest still pass.
=> VA-2686 Adding support for reporting interaction

.travis.yml, build.gradle, example-java-android/build.gradle, example-kotlin-android/build.gradle, gradle/wrapper/gradle-wrapper.properties
- Updating Android Gradle Plugin to version 3.0
- Updating Gradle version to 4.1
- Updating Android Build Tools version to 26.0.2
- Updating Android Support library in samples to version 26.1.0
- Updating Kotlin version in samples to 1.1.51
=> Android Gradle Plugin 3.0 Update

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java
[VA-2693](https://vimean.atlassian.net/browse/VA-2693)
Adding a synchronous version of emptyResponsePost to support live heartbeats.
=> VA-2693 Adding emptyResponsePostSync

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java
When calling `VimeoClient.initialize` with a configuration object, a new instance of `VimeoClient` is created every time. This PR uses an existing instance if there is one and sets the configuration object. If there isn't an existing VimeoClient object, then a new one is created with the configuration object.
=> Reuse VimeoClient for Initialization

vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/NotificationConnection.java
New detailed list of unseen notification counts.
- The existing `type_count` field contains a list of "new" notifications.
- The new `type_unseen_count` field contains a list of "unseen" notifications.
Run unit tests
=> Add new type_unseen_count filed to notifications connections object

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java
Certain `PUT` calls can return a `User` in the success callback. Since our `PUT` doesn't return a proper type, it requires us to make a second request for the `User`. We can eliminate one network request by properly returning the `User` when appropriate.
Make a `PUT` request to an endpoint that returns a `User` in its response.
=> Creating typed PUT method that returns User

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java
The PR #274 had changed `VimeoClient` to reuse the cached VimeoClient instance if it had been initialized. However, this change caused other issues. It requires further investigation on the best way to implement it. This PR reverts the changes `VimeoClient`.
=> Revert VimeoClient Initialization

build.gradle, example-java-android/src/main/java/com/vimeo/android/networking/example/TestApp.java, example-kotlin-android/src/main/kotlin/com/vimeo/android/networking/example/kotlin/TestApp.kt, vimeo-networking/src/main/java/com/vimeo/networking/interceptors/CacheControlInterceptor.java
It has come to our attention that caching has been broken for some time in the app. The cause of this was a change to the way the `CacheControlInterceptor` was constructed. Originally, the chain of events was:
1. `val response = chain.proceed(chain.request())`
2. `return response.newBuilder().header(correct cache headers).build()`
[This was changed last August to a different chain, which caused the headers to not be rewritten](https://github.com/vimeo/vimeo-networking-java/commit/3d4c8e7fcdb0fea7537f322459722300f1b84f89#diff-eb316d561736430dbe7d37edb608149aL43):
1. `val request = chain.request().newBuilder().header(new cache headers).build()`
2. `return chain.proceed(request)`
This resulted in the headers being overridden on the request, but not on the response. Since our problem is that …
=> Fixing Caching

vimeo-networking/src/main/java/com/vimeo/networking/RetrofitSetup.java, vimeo-networking/src/test/java/com/vimeo/networking/RetrofitSetupTest.kt
- https://github.com/vimeo/vimeo-networking-java/issues/273
If the consumer passed invalid characters to the user agent, the library would crash. We can avoid this by checking if the characters are invalid, and if they are, then just ignoring them. Using Okhttp's `Headers.Builder.set()` we can verify that characters pass its validity check. Unit tests verify the behavior.
Run the unit tests.
=> Fix for invalid characters in user agent

vimeo-networking/src/main/java/com/vimeo/networking/model/error/ErrorCode.java
New errors need to be included in the `ErrorCode` enum based on recent API changes. They are:
- `2507 - PRODUCT_NOT_FOUND`: Couldn't find a product matching the SKU.
- `3115 - INVALID_INPUT_RECEIPT_VALIDATION_UNSUCCESSFUL`: Receipt validation failed.
- No testing
=> Adding new receipt errors

vimeo-networking/src/main/java/com/vimeo/networking/model/error/ErrorCode.java
The API has added a new error code which we'd like to support.
The new error code is for total quota breach for basic users (currently 5gb)
Make a request to create an upload ticket providing the size of a video that will exceed a basic users total limit. If weekly limit (currently 500mb) is also exceeded by the video, that error will be returned instead.
=> Adding error code for upload quota cap exceeded

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
A new status was added to the `clip.status` field in version 3.4.1 of the API. The status is `total_cap_exceeded` and complements the `quota_exceeded` status, which was originally used to represent weekly and total limits being exceeded. In order to be more clear, this status was added to differentiate between weekly and total. Now each status has a different use case:
- `total_cap_exceeded`: used when the video exceeds the user's total storage cap (common for basic users who have a 5GB total limit.
- `quota_exceeded`: used when the video exceeds the user's weekly storage cap.
=> Adding total_cap_exceeded status

vimeo-networking/src/main/java/com/vimeo/networking/model/User.java, vimeo-networking/src/main/java/com/vimeo/networking/model/UserBadge.java
(If applicable)
- https://github.com/vimeo//vimeo-networking-java/issues/VA-3274
Added "producer" to the list of account types and badge types.
=> VA-3274 Adding support for producer account

vimeo-networking/src/main/java/com/vimeo/networking/Configuration.java, vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/interceptors/LanguageHeaderInterceptor.java
When requests are made, particularly with categories, we are supposed to be able to get a localized version back. On categories, this means a few titles will be in a different language. We need to tell the API that we want a different localization for a request.
Created a LanguageHeaderInterceptor to automatically add the `Accept-Language` header to HTTP requests made to the API. Done by passing in the user's locales to the Configuration Builder and then passing on the language codes to the interceptor. On devices that support multiple locales, a string of all the locales will be passed on and the API will select the first support locale. Defaults to English if none of the locales are supported.
- Go to Explore tab and check the current language of the category titles.
- Close Vimeo app …
=> Api category localization

vimeo-networking/src/main/java/com/vimeo/networking/model/Category.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Channel.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Comment.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Entity.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Group.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Picture.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Recommendation.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Tag.java, vimeo-networking/src/main/java/com/vimeo/networking/model/User.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java, vimeo-networking/src/main/java/com/vimeo/networking/model/tvod/Season.java
Various unique entities are represented by the Vimeo API. Each of these entities has a unique identifier. Here I have created an interface for a common way to access this identifier property, and have added the appropriate fields to each entity that was missing them.
The affected models are
- Category
- Channel
- Clip (Video)
- Comment
- Group
- Picture
- Recommendation
- Tag
- User
- Season
=> Entity representation

vimeo-networking/src/main/java/com/vimeo/networking/model/error/VimeoError.java, vimeo-networking/src/test/java/com/vimeo/networking/model/error/VimeoErrorTest.kt
The `VimeoError` class was not being properly deserialized from json because Gson was not calling the setter for `setRawErrorCode` and the `mErrorCode` field was never being set. The solution to this was to enable type adapter serialization for this class.
- Run the unit tests.
=> [BUG] VimeoError was not being properly deserialized

README.md, example-kotlin-android/build.gradle, vimeo-networking/build.gradle
https://github.com/vimeo/vimeo-networking-java/issues/285
https://vimean.atlassian.net/browse/ADF-299
https://github.com/vimeo/vimeo-networking-java/issues/289
https://vimean.atlassian.net/browse/ADF-297
Build conflicts were occurring related to `com.intellij:annotations`. This dependency was updated in the build script to the new version `org.jetbrains:annotations:16.0.2` and stag's annotations were excluded (since it also pulled in the older version of the lib). Exclusions were removed from the sample since they are no longer needed after the changes made to the build script.
- Create a test project as described in this issue:
https://github.com/vimeo/vimeo-networking-java/issues/285
- Confirm that it fails to build when pointing at the public version of networking.
- Use jitpack and …
=> ADF-299 annotations

.travis.yml, README.md, example/build.gradle, vimeo-networking/build.gradle
https://github.com/vimeo/vimeo-networking-java/issues/285
https://vimean.atlassian.net/browse/ADF-299
https://github.com/vimeo/vimeo-networking-java/issues/289
https://vimean.atlassian.net/browse/ADF-297
Build conflicts were occurring related to `com.intellij:annotations`. This dependency was updated in the build script to the new version `org.jetbrains:annotations:16.0.2` and stag's annotations were excluded (since it also pulled in the older version of the lib). 
- Create a test project as described in this issue:
https://github.com/vimeo/vimeo-networking-java/issues/285
- Confirm that it fails to build when pointing at the public version of networking.
- Use jitpack and point at the latest commit on this branch:
`implementation 'com.github.vimeo:vimeo-networking-java:7488ad96ac'`
- …
=> fixing annotations and updating tools and sdk on the sample

vimeo-networking/src/main/java/com/vimeo/networking/model/Privacy.java
Add new optional token used when casting videos via ChromeCast
For an app with the appropriate permissions the new field on `video.privacy` should be set.
=> Add new chromecast receiver token

vimeo-networking/src/main/java/com/vimeo/networking/model/Recommendation.java
`Recommendation` is the only model containing an `Entity` that does not allow those entities to be changed. We should add the ability to change these entity instances. Other models are mutable and have setters. Instead of making this class mutable, I have opted to add a constructor that can be used for copying from the previous `Recommendation` instance.
=> Adding full constructor to Recommendation for copy use

vimeo-networking/src/main/java/com/vimeo/networking/model/ConnectionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/upload/Gcs.java, vimeo-networking/src/main/java/com/vimeo/networking/upload/Upload.java
https://github.com/vimeo//vimeo-networking-java/issues/VA-3460
This ticket is about adding support for GCS to the upload object. Here is an example of the response format.
```
"gcs":[  
{  
"upload_link":"https://www.googleapis.com/upload/storage/...",
"start_byte":0,
"end_byte":1057148,
"metadata":{  
"connections":{  
"upload_attempt":{  
"uri":"/upload/attempt/09d...",
"options":[  
"GET"
]
}
}
}
}
]
```
No testing here. Can be confirmed on the application level.
=> VA-3460 Adding GCS Support

build.gradle, models/build.gradle, settings-parent.gradle, settings.gradle, vimeo-networking/build.gradle, vimeo-networking/src/main/java/com/vimeo/networking/AnnotatedConverterFactory.java, vimeo-networking/src/main/java/com/vimeo/networking/RetrofitSetup.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java, vimeo-networking/src/main/java/com/vimeo/networking/callers/MoshiGetRequestCaller.java
The purpose of this PR is to add support for the new models in the current implementation of `VimeoClient`.  Using the new models will require using Moshi for serialization and deserialization. The changes made to `VimeoClient` should be backward compatible. The client should be able to continue to use the old models. 
In order to achieve these requirements, these are the changes that were made:
1. [AdapterConverterFactory](https://github.com/vimeo/vimeo-networking-java/compare/v2.0.0...staff-picks-test?expand=1#diff-6ee966a68e85fa09ead8b7bf1389c920) was added to be able to use the Moshi or Gson converter with Retrofit. The converter that you wish to use should be specified as an annotation on `VimeoService`. Here is an example [Get users request using the new …
=> Update VimeoClient for using Moshi

vimeo-networking/src/main/java/com/vimeo/networking/AnnotatedConverterFactory.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java, vimeo-networking/src/main/java/com/vimeo/networking/callers/GetRequestCaller.java, vimeo-networking/src/main/java/com/vimeo/networking/callers/MoshiGetRequestCaller.java
Created new function in `VimeoService` and new `GetRequestCaller` field that allows for requesting an `AppConfiguration` object from the `/configs` endpoint. Additionally, a bug was fixed in the `AnnotatedConverterFactory` where the `requestBodyConverter` was never being created. I also did some refactoring in the factory to pull out the code searching for an annotation into a separate function.
=> Configuration request for new DTOs

vimeo-networking/src/main/java/com/vimeo/networking/model/playback/Play.java
It's a security concern that password protected videos can show up in lists and be fully playable. So now if the play files aren't available because it's password protected, it'll have a new status. This will not be behind a version and will get rolled out at some point in the future. Since it's additive, it shouldn't break any cache/existing logic.
Hit `api-video-play-status-password-api` as the base url and make a request for a likes list that has a password protected video in it (see my Android branch for a real example).
=> Adding password as play status

models/src/main/java/com/vimeo/networking2/LiveChatConfiguration.kt
Change api_id -> app_id in `LiveChatConfiguraiton` DTO.
=> Fix app id field name in live chat configuration

vimeo-networking/build.gradle, vimeo-networking/src/test/java/com/vimeo/networking/RetrofitSetupTest.kt, vimeo-networking/src/test/java/com/vimeo/networking/utils/BaseUrlInterceptorTest.java
We want to update retrofit to the latest version, as the current version being used is almost 3 years old and is lacking features that we want to use downstream of this library. We cannot just override the version used here downstream, as there are some API changes that seemed to cause build failures, so we are upgrading the library to 2.5.0.
Nothing in the library needed to be changed except for unit tests. Those tests:
- `RetrofitSetupTest`
- `BaseUrlInterceptorTest`
See the changelog for retrofit: https://github.com/square/retrofit/blob/master/CHANGELOG.md
- Run tests
- Verify that the library works correctly with the new version.
=> Updating retrofit to version 2.5.0

models/src/main/java/com/vimeo/networking2/FileTransferPage.kt, models/src/main/java/com/vimeo/networking2/Video.kt, vimeo-networking/src/main/java/com/vimeo/networking/model/FileTransferPage.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java, vimeo-networking/src/test/java/com/vimeo/networking/model/FileTransferPageTest.java
We need to add internal support for the file transfer page. The link to the transfer page is held by the transfer page object. The API adds the information to the video as `file_transfer.link`, so I have created the appropriate `FileTransferPage` DTO which mimics the way the `ReviewPage` DTO works.
I created a legacy DTO in Java in `vimeo-networking` and a new DTO in Kotlin in `models`.
=> File share DTO

auth/src/main/java/com/vimeo/networking2/internal/AuthenticatorImpl.kt, models/src/main/java/com/vimeo/networking2/internal/AuthParam.kt
Facebook authentication requires the Facebook token name to be `token` whereas the token name for Google should be `id_token`. I created an enum `SocialAuthType` to determine which token param field name to use in the `socialAuthenticate` method.
=> Update Facebook token field name

README.md, example-java-android/build.gradle, example-vimeo-networking2-android/build.gradle, vimeo-networking/build.gradle
I thought maybe that changing to `implementation` from `compile` would fix a dexing bug we were experiencing client side, but it turned out not to. Regardless, I decided that we could still change all the usage of `compile` to be consistent throughout the library.
I also removed the `compile` entry that added jars, since we had no jars we were explicitly adding from resources.
=> Converting compile to implementation

api/build.gradle, api/src/main/java/com/vimeo/networking2/ApiConstants.kt, api/src/main/java/com/vimeo/networking2/config/RetrofitSetupModule.kt, api/src/main/java/com/vimeo/networking2/config/ServerConfig.kt, auth/build.gradle, build.gradle, example-java-android/build.gradle, example-kotlin-android/build.gradle, example-vimeo-networking2-android/build.gradle, fastlane/Fastfile, gradle/wrapper/gradle-wrapper.properties, models/build.gradle, vimeo-networking/build.gradle
This PR implements certificate pinning for the new networking library. OkHttp 3 provides a way to specify a public key for a url pattern when setting up OkHttpClient. `RetrofitSetupModule` now has a method to do this. The `ServerConfig` object has a flag which is set to true by default to determine whether to setup SSL pinning or not. This is flag is checked in the module when setting up certificate pinning. 
This PR also fixes the issue that implementation and api were not being recognized by api, auth, models and vimeo-networking modules. This is because they were using the java gradle plugin. The java-library plugin does know about how to handle implementation vs api. They were updated in the specific gradle files.
=> Implement certificate ssl pinning 
