vimeo/vimeo-networking-java

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java
[VA-1364](https://vimean.atlassian.net/browse/VA-1364)
Implementing HTC Blinkfeed requires a synchronous call to fetch content
Added a synchronous version of fetchContent
Verify existing fetching works as expected, and synchronous fetching also works as expected.
=> VA-1364 sync fetch method

README.md
[VA-1370](https://vimean.atlassian.net/browse/VA-1370)
Update the ReadMe to detail obtaining a client id and client secret
Updated the read me and pointed to the docs in the API
=> VA-1370 Update the ReadMe with API Registration

vimeo-networking/src/main/java/com/vimeo/networking/model/FeedItem.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
[VA-1413](https://vimean.atlassian.net/browse/VA-1413)
Adding resource_key field for clip objects
Added the resourceKey field, and use it for comparison methods
Will need VA-1413 branch of the app for testing.
=> VA-1413 video resource key

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VideoFile.java
[VA-1432](https://vimean.atlassian.net/browse/VA-1432)
Part of download cleanup
* Adding in md5 field to video file for comparison
* Added convenience method in video for access a file by md5
* Added in synchronous getter for video object
* isExpired convenience method on VideoFile (originally in a util)
* Fetch videos sychronously
@kevinzetterstrom - it'd be nice to have you peep this as well
=> VA-1432 Cleanup Part 1

build.gradle
[VA-1532](https://vimean.atlassian.net/browse/VA-1532)
Update gradle
Update gradle
=> VA-1532 updating gradle version

build.gradle, vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VodItem.java
[VA-1618](https://vimean.atlassian.net/browse/VA-1618)
Updating model for VOD support.
Updating project gradle version. Adding filters for subscriptions, rentals, and purchases. Adding equals and hashCode support to VodItem object.
Ensure that networking continues to function as expected.
=> Va 1618 updating vod model

vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VideoFile.java
[VA-1543](https://vimean.atlassian.net/browse/VA-1543)
Stub out trailer/vod helper
* Added getters/setters for trailer and vod for testing
* Fixed fps bug since fps could be a double
=> VA-1543 vod and fps fix

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Connection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/ConnectionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Interaction.java, vimeo-networking/src/main/java/com/vimeo/networking/model/InteractionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VodItem.java
[VA-1618](https://vimean.atlassian.net/browse/VA-1618)
Adding model support for networking requirements of VOD.
Added totals to the Connection object for tracking viewable series counts.
Added purchase_time sort for sorting VODs by date purchased.
Added ondemand and trailer connections
Added stream and expiration to Interaction
Added buy, rent and subscribe to InteractionsCollection
Modified Video object to perform the actual calculations and method implemenations for VOD based on the supporting models
Added some annotations to existing objects
Added some convenience methods to VodItem
Make sure that no existing VOD and networking features are broken.
=> VA-1618: Added model support for final (hopefully) VOD requirements

vimeo-networking/src/main/java/com/vimeo/networking/utils/VimeoNetworkUtil.java
Relates to Android App PR:https://github.vimeows.com/MobileApps/Vimeo-Android/pull/619
[ANDTV-42](https://vimean.atlassian.net/browse/ANDTV-42)
Cleaning up organization structure of utilities across Vimeo applications
Moved this helper method from the internal Vimeo codebase to the networking codebase since it can provide use to others and seems like a good logical home.
Ensure calls are still cancelled in the context of streams.
=> ANDTV-42 Utility Class Organization

vimeo-networking/src/main/java/com/vimeo/networking/model/VodItem.java
[VA-1646](https://vimean.atlassian.net/browse/VA-1646)
Deeplinking for series VODs 
Added in a helper method to easily grab the number of viewable videos on a VOD item
=> VA-1646 add helper method for viewable video count

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java
[VA-1542](https://vimean.atlassian.net/browse/VA-1542)
Series container page to show viewable content
Adding a public filter for viewable VOD content
=> VA-1542 add viewable filter

example/build.gradle, vimeo-networking/build.gradle, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/callbacks/VimeoCallback.java, vimeo-networking/src/main/java/com/vimeo/networking/utils/VimeoNetworkUtil.java
[VA-1519](https://vimean.atlassian.net/browse/VA-1519)
Upgrade to Retrofit 2.0.2 from 2.0Beta3
Updated packages, and made the necessary changes. 
You can run a smoke test yourself, but I have gone through the Android app and tested various endpoints plus cert pinning using Charles.
=> VA-1519 Retrofit 2.0.2

vimeo-networking/src/main/java/com/vimeo/networking/model/VodItem.java
[VA-1542](https://vimean.atlassian.net/browse/VA-1542)
As a user, I want to see the series container page.
This is just a helper method to get the videos uri for a VodItem
=> VA-1542 VOD helper method

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java
[VA-1622](https://vimean.atlassian.net/browse/VA-1622)
Adding manual sort constant for series container requests.
Added a constant SORT_MANUAL = "manual" to Vimeo.java
Not much to test here. It is just a constant. Constants never hurt anyone.
=> adding manual sort

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VodItem.java
Merging dev branch into 2.3.1 branch to bring it up to date
=> Merge Dev into 2.3.1

vimeo-networking/src/main/java/com/vimeo/networking/model/Email.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Privacy.java, vimeo-networking/src/main/java/com/vimeo/networking/model/User.java
[VA-822](https://vimean.atlassian.net/browse/VA-822)
In order to determine if the current user is verified or not, we need to look at the verified emails sent back in the "emails" field by the API for the current authenticated user on the /me endpoint
I added in the necessary "emails" hooks to get the list of emails that the user has verified. A non-empty list indicates that the user is verified
hit the /me endpoint without any filters and see that the ArrayList<Email> is not empty if the user has verified an email.
=> VA-822 comments unverified

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java, vimeo-networking/src/main/java/com/vimeo/networking/model/PinCodeInfo.java, vimeo-networking/src/main/java/com/vimeo/networking/model/error/ErrorCode.java
[ANDTV-27](https://vimean.atlassian.net/browse/ANDTV-27)
Create the business logic related to pin code authentication in the networking layer. It needs to support the use case where a user is presented with a pin code and goes to a link to enter her/his user credentials while the app polls and endpoint until either the user has logged in or the pin code has expired. Details of the API are here:
https://drive.google.com/a/vimeo.com/file/d/0Bwy64gBzhJ8AUHVQVWFQQ0lqNlE/view
I added a method to VimeoClient called "logInWithPinCode" to be used in association with pin code based authentication for connected but keyboardless devices such as Android TV. The loginWithPinCode method takes two arguments: "pinCodeCallback" and "authCallback." The loginWithPinCode method …
=> ANDTV-27 Pincode Auth

vimeo-networking/src/main/java/com/vimeo/networking/model/BaseResponseList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/CategoryList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/ChannelList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/CommentList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/FeedList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/UserList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VideoList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VodList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/search/SearchResponse.java
Minor PR: updating the stag dependency to fix the crash we saw, and to support abstract types.
=> Update stag dependency

vimeo-networking/src/main/java/com/vimeo/networking/model/User.java, vimeo-networking/src/main/java/com/vimeo/networking/model/UserBadge.java
[VA-1807](https://vimean.atlassian.net/browse/VA-1807)
Add new user badges
Created the new badge model that is represented on the user object.
Detailed *list* of what to test and how to test it. Including all edge cases.
=> VA-1807 add new user badges

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java
[VA-1791](https://vimean.atlassian.net/browse/VA-1791)
Update play logging
I needed to tweak the constants used in play logging
=> VA-1791 play logging constants

vimeo-networking/src/main/java/com/vimeo/networking/model/error/ErrorCode.java, vimeo-networking/src/main/java/com/vimeo/networking/model/error/VimeoError.java
[VA-1789](https://vimean.atlassian.net/browse/VA-1789)
Update the error codes with new DRM error codes
Added a few new codes.
=> VA-1789 adding DRM error codes

README.md
[VA-1834](https://vimean.atlassian.net/browse/TICKET_NUMBER)
Better highlight call to ```initialize```. https://github.com/vimeo/vimeo-networking-java/issues/113
Updated the readme to reflect that initialize is mandatory.
=> VA-1834 update readme to detail initialize better

vimeo-networking/build.gradle, vimeo-networking/src/test/java/com/vimeo/networking/TestSetupValidation.java
Adding basic unit testing infrastructure.
=> Adding unit testing infrastructure

vimeo-networking/src/main/java/com/vimeo/networking/model/error/ErrorCode.java
[VA-1887](https://vimean.atlassian.net/browse/VA-1887)
New error codes for DRM
Added two new error codes that the API can send related to DRM
=> VA-1887 add new error codes for drm

vimeo-networking/src/main/java/com/vimeo/networking/model/Recommendation.java
[VA-1742](https://vimean.atlassian.net/browse/VA-1742)
Add getters to Recommendation for the recommendation cards
Added getters
=> VA-1742 add getters to Recommendation

vimeo-networking/src/main/java/com/vimeo/networking/model/playback/Play.java
[VA-1929](https://vimean.atlassian.net/browse/VA-1929)
We need to account for DRM files when counting files
Simple count++ when files exist
=> VA-1929 account for DRM files

vimeo-networking/src/main/java/com/vimeo/networking/model/playback/Play.java
[VA-1918](https://vimean.atlassian.net/browse/VA-1918)
We weren't getting the log links for drm videos
Check to see if the videofiles exist, if so, use them
The load, like press, and watchlater press logs should send now.
=> VA-1918 add log links for drm videos

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java
[VA-1741](https://vimean.atlassian.net/browse/VA-1741)
batch following of users/channels
The API request for the batch follow takes an array as the body, so we need support  for this.
=> VA-1741 adding post service that takes an array

vimeo-networking/src/main/java/com/vimeo/networking/model/ConnectionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/User.java
[ANDTV-168](https://vimean.atlassian.net/browse/ANDTV-168)
Add support for displaying channels on User Pages.
Added two convenience methods for getting channel connection data.
Nothing to test at this point.
=> ANDTV-168 Channels

vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
[ANDTV-134](https://vimean.atlassian.net/browse/ANDTV-134)
Make it so you can resume playback of a video if it has the progress object on it.
I added in multiple helpers and added javadocs to them
Make sure you have the capability to receive play progress and then look at vimeo.com/history and find a video that says it is resumable. Find that video in the app, and shaboom.
=> ANDTV-134 Resume Playback

vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java, vimeo-networking/src/main/java/com/vimeo/networking/model/playback/PlayProgress.java
Refer to https://github.com/vimeo/vimeo-networking-java/pull/137
=> ANDTV-134 Resume Playback V2

vimeo-networking/src/main/java/com/vimeo/networking/model/Category.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Channel.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Followable.java, vimeo-networking/src/main/java/com/vimeo/networking/model/User.java
[VA-1898](https://vimean.atlassian.net/browse/VA-1898)
While building onboarding, I needed a common interface for an item to be "Followable" so that I could execute follows on any one of several items.
Added the Followable interface that is implemented by Channels, Categories, and Users. Possibly it should be implemented by more model classes. Also, let me know if there should be any more methods that are a part of the Followable interface.
=> VA-1898 Add followable interface

vimeo-networking/src/main/java/com/vimeo/networking/model/ConnectionCollection.java
[VA-1899](https://vimean.atlassian.net/browse/VA-1899)
We want to get the recommended endpoints for users and channels from the API.
Added the user and channel recommendation connections to the ConnectionCollection
=> VA-1899 recommended endpoints

vimeo-networking/build.gradle
Updating to the latest version of stag, 1.0.1
=> Update to latest stag version

build.gradle
Updating to gradle 2.2.0 with the Android Studio update
=> New gradle version (2.2.0)

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java
[ANDTV-245](https://vimean.atlassian.net/browse/ANDTV-245)
We need a trending filter for the trending videos list on tv
A one liner
Nada
=> ANDTV-245 Adding trending

vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
[VA-1983](https://vimean.atlassian.net/browse/VA-1983)
We want to display a VOD Season name in the VOD list, this is about creating a helper for that.
I added a simple method to get the season name, and I moved the Play Status into the correct fold.
=> VA-1983 Add season name helper method to Video

vimeo-networking/src/main/java/com/vimeo/networking/model/ConnectionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/User.java
[ANDTV-216](https://vimean.atlassian.net/browse/ANDTV-216)
Adding watched_videos to user.metadata.connections to support watched history.
A trivial one-liner.
Nothing to test.
=> ANDTV-216 Adding watched videos

example/src/main/java/com/vimeo/android/networking/example/vimeonetworking/TestAccountStore.java, vimeo-networking/src/main/java/com/vimeo/networking/AccountStore.java, vimeo-networking/src/main/java/com/vimeo/networking/Configuration.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VimeoAccount.java
This reverts commit 008566e13be2fb86250f78043566d0d7e125ab19, reversing
changes made to a8d46757f2e1d8f0ba8d5e7f27d8a9816c6732d3.
=> Revert "Merge pull request #152 from vimeo/VA-1728"

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java
[ANDTV-221](https://vimean.atlassian.net/browse/ANDTV-221)
In an effort make all requests more filtered, we should add field filters to the Me request
Overloaded the fetchCurrentUser method, allowing for a field filter string to be passed in
=> ANDTV-221 add fetch method for me with field filter

gradle/wrapper/gradle-wrapper.properties, vimeo-networking/build.gradle
Just updating some stuff
- The gradle version
- The stag library version
=> Update to the latest stag library and gradle version

README.md, build.gradle, vimeo-networking/build.gradle
Update gradle, update stag, add build status info
=> Update gradle, update stag, add build status info

vimeo-networking/src/main/java/com/vimeo/networking/model/Spatial.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
Adding spatial data to the video object for 360 videos.
=> Add spatial data representation to video object

vimeo-networking/build.gradle, vimeo-networking/src/main/java/com/vimeo/networking/model/CategoryList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/ChannelList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/CommentList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/FeedList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Privacy.java, vimeo-networking/src/main/java/com/vimeo/networking/model/RecommendationList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/UserList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/VideoList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/NotificationList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/vod/SeasonList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/vod/VodList.java
- Updating to stag 2.0.1
- Fixing bug exposed by Stag where the type we exposed in `privacy.add` and `privacy.download` was integer instead of boolean.
=> Updating to Stag 2.0.1

README.md
This fixes a few outdated anchor pointers to our API authentication documentation.
=> Fixing some bad anchors to our API authentication docs.

vimeo-networking/src/main/java/com/vimeo/networking/model/User.java
[VA-2203](https://vimean.atlassian.net/browse/VA-2203)
For ease of use, add a helper to obtain the `NotificationConnection` off of the user
As described, I added a helper method
=> VA-2203 add helper for notification connection

.travis.yml, build.gradle, example/build.gradle, gradle/wrapper/gradle-wrapper.properties
=> updating gradle

vimeo-networking/src/main/java/com/vimeo/networking/model/InteractionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/SvodInteraction.java, vimeo-networking/src/main/java/com/vimeo/networking/model/User.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java, vimeo-networking/src/main/java/com/vimeo/networking/model/vod/SvodInteraction.java
[ADF-118](https://vimean.atlassian.net/browse/ADF-118)
We need to make changes to models for SVOD. The API side is not yet done, but the blueprint is here: https://github.vimeows.com/Vimeo-API/blueprint/pull/13/files
I added a new `Interaction` subclass, `SvodInteraction` to contain the interaction data specific to the SVOD representation.
I added helpers to access this interaction on `Video` and `User`
=> ADF-118 SVOD Model Changes

vimeo-networking/build.gradle
Updating stag library to version 2.1.1
=> Updating stag library

build.gradle
=> Update Gradle Version

vimeo-networking/build.gradle
=> Updating stag

vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/NotificationConnection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/NotificationConstants.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/NotificationType.java, vimeo-networking/src/main/java/com/vimeo/networking/model/notifications/Subscriptions.java
[VA-2321](https://vimean.atlassian.net/browse/VA-2321)
During a jam day, we decided to add a new notification to inform users of videos that have been uploaded by people they follow
This work is just about adding in the new notification on the networking side, the bulk of the work will be in a mobile PR
=> VA-2321 Followed user upload notification type

build.gradle
=> Updating gradle version

vimeo-networking/build.gradle
Stag 2.2.0
- Allows us to use private member variables and have setters instead
=> updating stag to 2.2.0

build.gradle
=> Updating gradle to 2.3.3

fastlane/Fastfile
[TICKET_NUMBER](https://vimean.atlassian.net/browse/TICKET_NUMBER)
A brief but thorough description of the ticket.
A brief but thorough description of the changes put in place to address the ticket.
Detailed *list* of what to test and how to test it. Including all edge cases.
=> Fastlane fixes to bintray publishing

.travis.yml, fastlane/Fastfile, fastlane/README.md, gradle.properties, vimeo-networking/build.gradle
[CI-450](https://vimean.atlassian.net/browse/CI-450)
publish to JCenter
=> CI-450:  publish to JCenter

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java
In order to be able to mock `VimeoClient` during tests with Mockito, the PR makes `Vimeo` non final.
=> VimeoClient Not Final

build.gradle, example-kotlin-android/src/main/kotlin/com/vimeo/android/networking/example/kotlin/vimeonetworking/NetworkingLogger.kt
Updated Kotlin version to 1.1.2-5.
=> Update Kotlin version

vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
Adding more documentation around TVOD/SVOD methods
=> Adding more documentation around TVOD/SVOD methods

vimeo-networking/build.gradle, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java, vimeo-networking/src/main/java/com/vimeo/networking/model/ConnectionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/TextTrack.java, vimeo-networking/src/main/java/com/vimeo/networking/model/TextTrackList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
- Added endpoint  for `/videos/video_id/texttracks` in `VimeoClient`.
- Added DTOs `TextTrackList` and `TextTrack`.
- Added text tracks connection on video object.
```
final String uri = video.getTexttracksConnection().getUri();
VimeoClient.getInstance().getTextTrackList(uri, new ModelCallback<TextTrackList>() {
@Override
public void success(TextTrackList textTrackList) {
// show captions
}
@Override
public void failure(VimeoError error) {
// handle error
}
}).
```
=> Add Text Tracking Request

build.gradle, vimeo-networking/build.gradle, vimeo-networking/src/main/java/com/vimeo/networking/model/BaseResponseList.java
In order to be able to mutate a response list, getters and setters were added to it. The fields in `BaseResponseList` were made private as Stag now supports it.
=> Added getters and setters to BaseReponseList

README.md
=> Fixing readme for example URL

README.md
=> update readme to reflect WebView decision

vimeo-networking/build.gradle, vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java, vimeo-networking/src/main/java/com/vimeo/networking/model/ConnectionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/ReviewPage.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java, vimeo-networking/src/test/java/com/vimeo/networking/model/ReviewPageTest.kt
[ADF-235](https://vimean.atlassian.net/browse/ADF-235)
We need to update our API version to 3.3.10 for Live
Updated the version, and handled the changes needed in https://developer.vimeo.com/api/changelog
Checkout this branch, and using the Vimeo App, do a regression test. This will all be heavily tested by QA before merging into our v2.0.0 branch.
=> Live: Api version update 3.3.10

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Live.java, vimeo-networking/src/main/java/com/vimeo/networking/model/LiveQuota.java, vimeo-networking/src/main/java/com/vimeo/networking/model/LiveStreamsQuota.java, vimeo-networking/src/main/java/com/vimeo/networking/model/LiveTime.java, vimeo-networking/src/main/java/com/vimeo/networking/model/User.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java, vimeo-networking/src/test/java/com/vimeo/networking/model/LiveQuotaTest.kt, vimeo-networking/src/test/java/com/vimeo/networking/model/LiveStreamsQuotaTest.kt, vimeo-networking/src/test/java/com/vimeo/networking/model/LiveTimeTest.kt
[VA-2656](https://vimean.atlassian.net/browse/VA-2656)
We need to update from 3.3.10 to 3.3.12 to add a few new fields for live. 
https://developer.vimeo.com/api/changelog
I added the new fields according to the changelog and the blueprint.
=> Update to version 3.3.12

gradle.properties
Update the library's version in `gradle.properties`, so that the proper version is reflected in the user agent.
=> Update Library Version

README.md
https://github.com/vimeo/vimeo-networking-java/issues/260
Clarifying initialization section of readme.
=> Readme: clarify initialization

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java, vimeo-networking/src/main/java/com/vimeo/networking/callbacks/VimeoCallback.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Live.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java, vimeo-networking/src/main/java/com/vimeo/networking/model/live/Live.java, vimeo-networking/src/main/java/com/vimeo/networking/utils/VimeoNetworkUtil.java
Add archiving and arching error live statues.
Added archiving and arching error live statues to `Live` .
N/A
=> Add New Live Statuses 

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java, vimeo-networking/src/main/java/com/vimeo/networking/callers/GetRequestCaller.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Interaction.java, vimeo-networking/src/main/java/com/vimeo/networking/model/InteractionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/iap/Product.java, vimeo-networking/src/main/java/com/vimeo/networking/model/iap/Products.java, vimeo-networking/src/test/java/com/vimeo/networking/model/iap/ProductTest.kt, vimeo-networking/src/test/java/com/vimeo/networking/model/iap/ProductsTest.kt
[VA-2723](https://vimean.atlassian.net/browse/VA-2723)
Added `/products`, `/products/123`, `/me/purchase/123` endpoints
Updated VimeoClient, VimeoService, and created/updated models to support IAP endpoints.
Unit test + internal drakov server testing complete.
=> IAP endpoints

build.gradle, vimeo-networking/build.gradle
We're a few versions behind the latest stag version, we should update to the latest version. What we get (that could be important):
- Small perf improvements on loading the factory
- Numerous bug fixes related to serialization
=> Stag version update

vimeo-networking/src/main/java/com/vimeo/networking/model/User.java
Internal - VA-2996
Adding support for live_premium account
Testing will come at the app level.
=> VA-2996 premium account

vimeo-networking/src/main/java/com/vimeo/networking/model/ConnectionCollection.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
Added a connection on the video object to get users who could view the video.
Verify the connection "user_with_access" is given back to you in the video object.
=> Add users with access connection

gradle.properties, vimeo-networking/src/main/java/com/vimeo/networking/model/Picture.java
- Added `link_with_play_button` field to Picture DTO.
- Bumped version to v1.1.2.
=> Added field link_with_play_button to Picture

vimeo-networking/src/main/java/com/vimeo/networking/model/Picture.java
Added `link_with_play_button` field to the `Picture` DTO.
=> Add link_with_play_button field to Picture

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java
Add constants for `duration` and `last_user_action_event_date` sorting options.
=> Add Duration and User Action Date Sorting Option

README.md
The README is out of date and is lacking the workaround for some compiler conflicts. This PR pulls the changes made on the `develop` branch into the `master` branch.
=> Updating README on master branch with new version

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java
Added sorting options:
- plays
- likes
- modified_time
- comments
=> Add more sorting options

vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java
I thought the fieldFilter documentation was a bit poorly explained. I decided to improve on it. 
Sorry if the formatting is a bit off. I did this in the Github file editor.
Tweaked some links and documentation.
=> Improve fieldFilter documentation

README.md
The requirements for getting the play object have changed. We need to modify our documentation accordingly.
=> Updating readme based on new requirements

vimeo-networking/src/main/java/com/vimeo/networking/model/error/ErrorCode.java
Map new `INVALID_INPUT_GOOGLE_RECEIPT_VALIDATION_FAILED` code to enum value in `ErrorCode.java`
N/A -- run tests
=> Add receipt failure validation code

models/build.gradle, models/src/main/java/com/vimeo/networking2/Category.kt, models/src/main/java/com/vimeo/networking2/Channel.kt, models/src/main/java/com/vimeo/networking2/Comment.kt, models/src/main/java/com/vimeo/networking2/Entity.kt, models/src/main/java/com/vimeo/networking2/Group.kt, models/src/main/java/com/vimeo/networking2/Picture.kt, models/src/main/java/com/vimeo/networking2/Recommendation.kt, models/src/main/java/com/vimeo/networking2/Season.kt, models/src/main/java/com/vimeo/networking2/Tag.kt, models/src/main/java/com/vimeo/networking2/User.kt, models/src/main/java/com/vimeo/networking2/Video.kt
Created entity interface in Kotlin to get a unique identifier for an object.
```
interface Entity {
val identifier: String?
}
```
All models with resource keys should inherit this interface.  These are the models that were updated:
- Category
- Channel
- Comment
- Group
- Recommendation 
- Tag
- Season
- User
- Video
=> Add Entity Interface

models/src/main/java/com/vimeo/networking2/AlbumList.kt, models/src/main/java/com/vimeo/networking2/CategoryList.kt, models/src/main/java/com/vimeo/networking2/ChannelList.kt, models/src/main/java/com/vimeo/networking2/CinemaList.kt, models/src/main/java/com/vimeo/networking2/CommentList.kt, models/src/main/java/com/vimeo/networking2/FeedItem.kt, models/src/main/java/com/vimeo/networking2/FeedItemConnections.kt, models/src/main/java/com/vimeo/networking2/FeedList.kt, models/src/main/java/com/vimeo/networking2/NotificationList.kt, models/src/main/java/com/vimeo/networking2/Paging.kt, models/src/main/java/com/vimeo/networking2/ProductList.kt, models/src/main/java/com/vimeo/networking2/RecommendationList.kt, models/src/main/java/com/vimeo/networking2/SearchResultList.kt, models/src/main/java/com/vimeo/networking2/SeasonList.kt, models/src/main/java/com/vimeo/networking2/TVoidItemList.kt, models/src/main/java/com/vimeo/networking2/UserList.kt, models/src/main/java/com/vimeo/networking2/VideoList.kt, models/src/main/java/com/vimeo/networking2/enums/AttributionType.kt
- Added feed list model
- Added Moshi Annotations for all Pageable models.
=> Add Feed Models

vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java, vimeo-networking/src/main/java/com/vimeo/networking/callers/GetRequestCaller.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Album.java, vimeo-networking/src/main/java/com/vimeo/networking/model/AlbumEmbed.java, vimeo-networking/src/main/java/com/vimeo/networking/model/AlbumList.java, vimeo-networking/src/main/java/com/vimeo/networking/model/AlbumPrivacy.java, vimeo-networking/src/main/java/com/vimeo/networking/model/InteractionCollection.java
https://github.com/vimeo//vimeo-networking-java/issues/VA-3570
This ticket is about adding albums support to the library. The `Album` data type will be added along with the related data classes and request support necessary to get `Album` information from the API.
No testing necessary at this point.
=> VA-3570 Adding support for albums

models/src/main/java/com/vimeo/networking2/VimeoAccount.kt
Add `User` object to `VimeoAccount`.
=> Add user object to vimeo account

.travis.yml, build.gradle, example/build.gradle, example/src/main/java/com/vimeo/android/networking/example/MainActivity.java, example/src/main/java/com/vimeo/android/networking/example/TestApp.java, example/src/main/res/values/strings.xml, fastlane/Fastfile, gradle/wrapper/gradle-wrapper.properties, vimeo-networking/build.gradle
1. Updated the following dependencies:
- Android Gradle Plugin
- Gradle Bintray Plugin
- Example app's target SDK, build tools version and support library.
- Gradle APT Plugin
2. Fixed lint errors in example app.
=> Update dependencies for version 1.1.3

models/src/main/java/com/vimeo/networking2/TrialEligibility.kt, models/src/test/java/com/vimeo/networking2/ModelsTest.kt, vimeo-networking/src/main/java/com/vimeo/networking/model/Subscription.java, vimeo-networking/src/main/java/com/vimeo/networking/model/SubscriptionRenewal.java, vimeo-networking/src/main/java/com/vimeo/networking/model/SubscriptionTrial.java, vimeo-networking/src/main/java/com/vimeo/networking/model/TrialEligibility.java, vimeo-networking/src/test/java/com/vimeo/networking/model/SubscriptionRenewalTest.java, vimeo-networking/src/test/java/com/vimeo/networking/model/SubscriptionTest.java, vimeo-networking/src/test/java/com/vimeo/networking/model/SubscriptionTrialTest.java, vimeo-networking/src/test/java/com/vimeo/networking/model/TrialEligibilityTest.java
VA-3736
New DTOs used for Trial Eligibility requests (internal).
Also added missing copyright notices from #358 and Unit tests.
Run unit tests.
=> Trial Eligibility DTOs

example/build.gradle, example/src/main/java/com/vimeo/android/networking/example/TestApp.java, example/src/main/res/values/strings.xml, gradle.properties, vimeo-networking/build.gradle
Version bump to 1.1.3 in master.
- Fixed failed builds on JitPack.
- Updated dependencies
=> Update version to 1.1.3

models/src/main/java/com/vimeo/networking2/SubscriptionRenewal.kt, models/src/main/java/com/vimeo/networking2/SubscriptionTrial.kt, vimeo-networking/src/main/java/com/vimeo/networking/model/SubscriptionRenewal.java, vimeo-networking/src/main/java/com/vimeo/networking/model/SubscriptionTrial.java
VA-3742
- Adds `renewal_date` field to `SubscriptionRenewal` DTOs 
- Add `has_been_in_free_trial` field to `SubscriptionTrial` DTOs 
Run unit tests
=> Membership dto updates

models/src/main/java/com/vimeo/networking2/enums/ViewPrivacyType.kt, vimeo-networking/src/main/java/com/vimeo/networking/model/Privacy.java, vimeo-networking/src/main/java/com/vimeo/networking/model/Video.java
https://github.com/vimeo//vimeo-networking-java/issues/VA-3864
Adding basic support for stock videos.
Nothing to test at this level. Check the app.
=> VA-3864 stock videos

vimeo-networking/src/main/java/com/vimeo/networking/Vimeo.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoClient.java, vimeo-networking/src/main/java/com/vimeo/networking/VimeoService.java, vimeo-networking/src/main/java/com/vimeo/networking/utils/VimeoNetworkUtil.java
https://github.com/vimeo//vimeo-networking-java/issues/VA-3792
Support the ability for users to add, delete, and edit albums. Album editing includes changing title, description, and privacy as well as adding and removing videos. 
Tests can be performed on the application level.
=> VA-3792 Album editing

build.gradle
Update Android Gradle plugin to 3.3.2.
=> Update Android Gradle Plugin
